### ISSUE TITLE
[Norton] IDP.Generic virus threat report

### ISSUE THREAD

**Issue by LuckyLuuk12** [likelovewant/ollama-for-amd#32]
### What is the issue?

Whenever I try to run the `rocm_v6.1/ollama_llama_server,exe` it is getting blocked by Norton because of a "severe threat" : "file infected with IDP.Generic virus". 

I don't know if it has anything to do with it but the past month I started using this Ollama, I also had to repeatedly 'tell Norton' that the "incorrectly / not- signed ollama_server.exe software is allowed to run on my pc" up to this point where it got completely blocked now.

### OS

Windows 10

### GPU

AMD Ryzen 7 5800X   8-core

### CPU

AMD Radeon RX 6600

### Ollama version

Cannot tell because the .exe got blocked

**Comment by likelovewant** [comment]
From version 0.4.0 onward,  instead of having a 'rocm_v6.1' directory, now called 'rocm' folder.If you were using the 'tag v6.1' and run into problems with the new files, it probably means you're using an older version.Updating to the latest release should resolve this.
If problems persist, similar issues have been reported on GitHub (https://github.com/ollama/ollama/issues/4134).
 file a ticket to Norton would helps.

**Comment by LuckyLuuk12** [comment]
Seems that the latest version indeed doesn't get blocked by Norton, thank you
